// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    Navbar: typeof import('./src/components/base-menu/index.vue')['default']
  }
}

export { }
